name: Pull Request

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Lint
        run: |
          go get -u golang.org/lint/golint
          golint -set_exit_status ./...
  test:
    strategy:
      matrix:
        go-version:
          - 1.15.x
        platform:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Run tests
        run: |
          go test ./... -coverprofile coverage.out

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.104.1
          args: --snapshot --skip-publish --debug